CREATE OR REPLACE PROCEDURE MANIPULATION_INFO(IN MANIP_NAME VARCHAR(20), OUT MANIP_PRICE DECIMAL(3))
    LANGUAGE SQL
BEGIN
    DECLARE V_NAME VARCHAR(20);
    DECLARE V_PRICE DECIMAL(3);

    DECLARE C1 CURSOR FOR SELECT NAME_M, PRICE
                          FROM MANIPULATIONS
                          WHERE NAME_M = MANIP_NAME;

    OPEN C1;
    FETCH C1 INTO V_NAME, V_PRICE;
    CLOSE C1;
    SET MANIP_PRICE = V_PRICE;
END;

BEGIN
    DECLARE NAME_M VARCHAR(20) DEFAULT 'X-ray';
    DECLARE PRICE DECIMAL(3);
    CALL FN72047.MANIPULATION_INFO(NAME_M, PRICE);
    CALL DBMS_OUTPUT.PUT_LINE('MANIPULATION ' || NAME_M || ' HAVE PRICE ' || PRICE);
END;

-------------------------------------------

CREATE OR REPLACE PROCEDURE BONUS_STAFF(IN NAME VARCHAR(50), IN V_BONUS DECIMAL(6,2), OUT NEW_SALARY DECIMAL(6,2))
    LANGUAGE SQL
BEGIN
    DECLARE V_NAME_S VARCHAR(50);
    DECLARE V_SALARY DECIMAL(6,2);
    DECLARE NULL_BONUS CONDITION FOR SQLSTATE '22004';

    DECLARE C1 CURSOR FOR SELECT NAME_S, SALARY
                          FROM STAFF
                          WHERE NAME_S = NAME;

    DECLARE CONTINUE HANDLER FOR NULL_BONUS
        RESIGNAL SQLSTATE '72047' SET MESSAGE_TEXT = 'STAFF HAS NO BONUS';

    OPEN C1;
    FETCH C1 INTO V_NAME_S, V_SALARY;

    IF coalesce(V_BONUS, 0) = 0 THEN
        SIGNAL NULL_BONUS
            SET MESSAGE_TEXT ='THE BONUS IS NULL';
    ELSE
        SET NEW_SALARY = V_BONUS + V_SALARY;
    END IF;
    CLOSE C1;

END;

BEGIN
    DECLARE NAME VARCHAR(50) DEFAULT 'Valya Mitova';
    DECLARE BONUS DECIMAL(6,2) DEFAULT 50;
    DECLARE NEW_SALARY DECIMAL(6,2);
    CALL FN72047.BONUS_STAFF(NAME, BONUS, NEW_SALARY);
    CALL DBMS_OUTPUT.PUT_LINE('New salary is = ' || NEW_SALARY);
END;

-------------------------------------------

CREATE OR REPLACE PROCEDURE DISPLAY_STAFF()
    LANGUAGE SQL
BEGIN
    DECLARE V_NAME_S VARCHAR(50);
    DECLARE V_POSITION_S VARCHAR(30);
    DECLARE V_NAME_VETERINARY_CLINIC VARCHAR(20);
    DECLARE I, CNT_STAFF INT DEFAULT 0;

    DECLARE C1 CURSOR FOR SELECT NAME_S, POSITION_S, NAME_VETERINARY_CLINIC
                          FROM STAFF;

    SELECT COUNT(*)
    INTO CNT_STAFF
    FROM STAFF;

    OPEN C1;

    WHILE (I < CNT_STAFF)
        DO
            FETCH C1 INTO V_NAME_S, V_POSITION_S, V_NAME_VETERINARY_CLINIC;
            CALL DBMS_OUTPUT.PUT_LINE(V_NAME_S || ' is a ' || V_POSITION_S || ' and work in ' ||
                                      V_NAME_VETERINARY_CLINIC);

            SET I = I + 1;
        END WHILE;
    CLOSE C1;
END;

CALL FN72047.DISPLAY_STAFF();
