CREATE TRIGGER TRIGG_BEFORE_UPDATE_STAFF
    BEFORE UPDATE OF SALARY
    ON STAFF
    REFERENCING NEW AS N OLD AS O
    FOR EACH ROW
BEGIN
    IF O.SALARY = N.SALARY THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Error: Salary has not been updated.'; -- 45000 - Необработено дефинирано от потребителя изключение.
    END IF;
END;

UPDATE STAFF
SET SALARY = 1500
WHERE NAME_S = 'Valya Mitova';
--------------------------------
CREATE OR REPLACE PROCEDURE DISPLAY_S()
    LANGUAGE SQL
BEGIN
    DECLARE V_NAME_S VARCHAR(50);
    DECLARE V_POSITION_S VARCHAR(30);
    DECLARE V_NAME_VETERINARY_CLINIC VARCHAR(20);
    DECLARE I, CNT_STAFF INT DEFAULT 0;

    DECLARE C1 CURSOR FOR SELECT NAME_S, POSITION_S, NAME_VETERINARY_CLINIC
                          FROM STAFF;

    SELECT COUNT(*)
    INTO CNT_STAFF
    FROM STAFF;

    OPEN C1;

    WHILE (I < CNT_STAFF)
        DO
            FETCH C1 INTO V_NAME_S, V_POSITION_S, V_NAME_VETERINARY_CLINIC;
            CALL DBMS_OUTPUT.PUT_LINE(V_NAME_S || ' is a ' || V_POSITION_S || ' and work in ' ||
                                      V_NAME_VETERINARY_CLINIC);

            SET I = I + 1;
        END WHILE;
    CLOSE C1;
END;

drop trigger TRIGG_AFTER_DELETE_STAFF;

CREATE TRIGGER TRIGG_AFTER_DELETE_STAFF
    AFTER DELETE ON STAFF
    REFERENCING OLD AS O
    FOR EACH ROW
BEGIN
    CALL DBMS_OUTPUT.PUT_LINE('DELETED STAFF IS ' || O.NAME_S);
    CALL DBMS_OUTPUT.PUT_LINE('ALL STAFF IS ');
    CALL FN72047.DISPLAY_S();
END;

DELETE FROM STAFF WHERE NAME_S = 'Valya Mitova';

CALL FN72047.DISPLAY_S();