CREATE FUNCTION FUNCTION1(PHONE_S VARCHAR(11))
RETURNS VARCHAR(50)
BEGIN
    RETURN
    (SELECT NAME_P
    FROM PATIENT
    WHERE PHONE_S = PHONE_OWNER);
END;

VALUES FN72047.FUNCTION1('0881234567');

CREATE FUNCTION FUNCTION2(NAME_P VARCHAR(50))
RETURNS VARCHAR(20)
BEGIN
    RETURN
    (SELECT NAME_M
    FROM MANIPULATIONS
    WHERE NAME_P = NAME_PATIENT);
END;

VALUES FN72047.FUNCTION2('Kai');