SET SCHEMA FN72047;

CREATE VIEW INFO
    AS
      SELECT S.NAME_S,P.NAME_P, P.BREED
      FROM STAFF S, PATIENT P
      WHERE S.PHONE_S = P.PHONE_OWNER;

SELECT * FROM INFO;

CREATE VIEW INFO2
    AS
     SELECT O.NAME_O, P.NAME_P, P.BREED
     FROM OWNER O, PATIENT P
     WHERE O.PHONE_O = P.PHONE_OWNER;

SELECT * FROM INFO2;